<?php
return [
    'CONFIG_FILE_NOT_EXIST' => '配置文件%s未能被找到',
    'CONFIG_CONTENT_NOT_EXIST' => '配置项%s在%s配置文件中未能被找到',
    'INVALID_ARGUMENT' => '%s参数错误',
    'CANT_EMPTY' => '%s参数不能为空',
    'EMAIL_FORMAT_ERROR' => '邮箱格式不正确',
    'QQ_FORMAT_ERROR' => 'qq格式不正确',
    'URL_FORMAT_ERROR' => 'url地址格式不正确',
    'PHONE_FORMAT_ERROR' => '手机号码格式不正确',
    'IDCARD_FORMAT_ERROR' => '身份证号格式不正确',
    'PASSWORD_ERROR' => '用户名和密码错误',
    'SYS_MCRYPT_DECODE_MD5_CHECK_ERROR' => '解密失败',
    'UNLOGINED' => '尚未登录',
    'ENV_EMPTY_ERROR' => '%s不能为空但为空了',
    'GAMETYPE_NOT_MATCH' => '未能匹配到对应的gametype：%s',
    'USER_NOT_EXIST' => '%s用户在DB中未能找到',
    'SERVICE_NOT_FOUND' => '未找到服务：%s',
    'OBJECT_EMPTY' => '请求的对象不存在',
    'METHOD_NOT_ALLOW' => 'method:%s不在允许的范围内',
    'URL_FORMAT_ERROR' => 'url格式不正确',
    'RETURNHEADER_FORMAT_ERROR' => 'returnheader必须为boolean类型',
    'METHOD_EMPTY_ERROR' => 'method为空',
    'URL_EMPTY_ERROR' => 'url为空',
    'CDN_SYNC_ERROR' => 'CDN同步运行失败',
    'FILE_SYNC_ERROR' => '文件同步运行失败',
    'UNLOGIN_OR_NO_GAMETYPE_ERROR' => '当前用户未登录或未选择gametype值',
    'CUR_USER_HAS_NO_GAMETYPE_AUTH' => '当前用户没有任何game的访问权限',
    'NO_POWER_TO_VIEW_THIS_GAMETYPE' => '当前用户没有对该游戏归类的访问权限',
    'NEED_ADMIN_POWER' => '该项操作需要管理员权限',
    'USER_ALREADY_EXIST' => '该用户已经存在',
    'CDNSYNC_TYPE_ERROR' => '错误的cdn同步类型',
    'CDN_SYNC_OFTEN' => 'cdn推送过于频繁，请稍候再试'
];